In [3]:
#
# SNAデータの表示とグラフ描画
#

import streamlit as st
import pandas as pd

import re
import subprocess
import os

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
plt.rcParams['font.family'] = 'Hiragino Sans'

In [12]:
#
# 環境設定
#

folder_path='MacroData/SNA/'
file_name = 'SNA_data.csv'

#sw_data = 'local'
sw_data = 'server'

sw_run = True
#sw_run = False

In [4]:
def open_by_excel(df, file_name = 'out', folder_path='MacroData/SNA/',
            sheet_name='データ'):
    file_name = file_name+'.xlsx'
    file_path = folder_path + file_name
    # Excel に保存
    df.to_excel(file_path, index=True, sheet_name=sheet_name)
    # ファイルを開く（Mac: 'open' / Windows: 'start' / Linux: 'xdg-open'）
    subprocess.run(['open', file_path])

In [16]:
#
# データの読み込み
#

file_name = 'SNA_data.csv'

if sw_data == 'server':
    url = "https://ymaeda.jp/data/"+file_name
    df = pd.read_csv(url, index_col=0, encoding='utf-8-sig')
else:
    file_path=folder_path+file_name
    df = pd.read_csv(file_path, index_col=0, encoding='utf-8-sig')

df.columns = df.columns.astype(str)

In [18]:
df.head()

,項目,1994,1995,1996,1997,1998,1999,2000,2001,2002,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,雇用者報酬,261592.9,265944.8,270561.6,278619.7,274439.0,269117.5,269760.7,266480.0,257309.9,...,257408.0,260504.9,267291.8,271992.2,281235.3,286784.6,283079.0,288639.6,295260.4,301191.9
1,営業余剰・混合所得,103376.6,107359.4,113180.0,108910.6,102785.4,102138.0,108238.6,105087.9,110890.5,...,97303.9,107776.2,106962.2,108621.0,99956.0,92766.6,75906.4,77772.5,73075.1,95797.4
2,固定資本減耗,114771.1,114960.3,117024.0,121647.3,123674.1,123314.3,123976.0,123253.3,122701.7,...,126196.3,128136.3,128196.2,130074.1,132398.7,134468.5,135600.0,138771.6,145677.1,150307.8
3,生産・輸入品に課される税,32817.8,34012.7,34911.0,36732.9,38471.9,39403.9,38704.8,38258.1,37768.3,...,41014.6,44861.9,45205.7,45525.7,45914.8,46470.3,47931.9,50513.9,52621.3,53460.7
4,（控除）補助金,3851.4,4053.0,3928.8,4062.9,3458.6,4132.6,4587.0,3985.0,3689.9,...,3296.4,3298.6,3265.1,3007.2,2938.2,3024.3,3228.7,3520.4,5857.0,8175.8

In [ ]:
#
# streamlit（開始）
#

st.title("データフレームの表示例")
st.dataframe(df)  # インタラクティブな表形式で表示（スクロールや並べ替えが可能）

# 項目リストを表示（複数選択可）
selected_items = st.multiselect("表示する項目を選んでください", df.index.tolist())

In [ ]:
#
# ボタンで描画実行
#

if st.button("グラフを描画"):
    if not selected_items:
        st.warning("少なくとも1つの項目を選んでください。")
    else:
        st.subheader("選択項目の時系列グラフ")
        fig, ax = plt.subplots()
        for item in selected_items:
            ax.plot(df.columns, df.loc[item], label=item, marker='o')
        ax.set_xlabel("年")
        ax.set_ylabel("値")
        ax.set_title("選択した項目の推移")
        ax.legend()
        ax.grid(True)

        # ✅ 年のラベルが重ならないように回転と位置調整
        plt.xticks(rotation=45, ha='right')

        # ✅ Y軸に3桁カンマを追加
        ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f"{int(x):,}"))

        st.pyplot(fig)

In [20]:
#
#  ＜＜＜ SNA.pyに変換 ＞＞＞
#

!jupyter nbconvert --to python streamlit_data_SNA.ipynb
!mv streamlit_data_SNA.py  SNA.py

#
# プログラムの「'get_ipython()'」以下を削除するプログラム
#

file_name='SNA.py'
program_list=[]
with open(file_name) as f:
    program_list.append(f.readlines())

min_no_list=[i for i,x in enumerate(program_list[0]) if 'get_ipython()' in x]
if min_no_list!=[]:
    print(min_no_list)
    min_no=min(min_no_list)
    program_list=program_list[0][:min_no]
    with open(file_name, mode='w') as f:
        f.writelines(program_list)

if sw_run:
    ! streamlit run SNA.py

[NbConvertApp] Converting notebook streamlit_data_SNA.ipynb to python
[NbConvertApp] Writing 2728 bytes to streamlit_data_SNA.py
[152, 153, 156, 164, 173]

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://192.168.3.7:8502

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog

^C
  Stopping...